# Generated by Django 3.1.7 on 2021-03-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_remove_fileinfo_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='InsterTime',
            field=models.TextField(default=0, verbose_name='InsterTime'),
        ),
    ]
