# Generated by Django 3.1.7 on 2021-03-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_auto_20210331_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installapp',
            name='InsterTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='InsterTime'),
        ),
    ]
