# Generated by Django 3.1.7 on 2021-04-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0005_auto_20210331_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AName', models.TextField(default='', verbose_name='软件名')),
                ('AVer', models.TextField(default='', verbose_name='软件版本')),
                ('ACompany', models.TextField(default='', verbose_name='软件厂家')),
                ('AInTime', models.TextField(default='', verbose_name='安装时间')),
                ('AUninstall', models.TextField(default='', verbose_name='软件卸载信息')),
                ('AALink', models.TextField(default='', verbose_name='软件网址')),
                ('AILink', models.TextField(default='', verbose_name='软件信息网址')),
                ('AULink', models.TextField(default='', verbose_name='软件更新地址')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserBroFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.TextField(default='', verbose_name='计算机ID')),
                ('Domain', models.TextField(default='', verbose_name='域名')),
                ('Ip', models.TextField(default='', verbose_name='IP')),
                ('PName', models.TextField(default='', verbose_name='进程（全路径）')),
                ('FileName', models.TextField(default='', verbose_name='下载文件名')),
                ('FileSize', models.IntegerField(default=0, verbose_name='下载文件大小')),
                ('FileMd5', models.TextField(default='', verbose_name='下载文件MD5')),
                ('FCTime', models.TextField(default='', verbose_name='下载文件创建时间')),
                ('KeyDesc', models.TextField(default='', verbose_name='描述')),
                ('sTag', models.IntegerField(default=0, verbose_name='1敏感文件、2木马文件')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.TextField(default='', verbose_name='计算机ID')),
                ('VName', models.TextField(default='', verbose_name='USB设备卷名')),
                ('DName', models.TextField(default='', verbose_name='USB设备名')),
                ('DModel', models.TextField(default='', verbose_name='USB设备厂家')),
                ('SNumber', models.TextField(default='', verbose_name='USB设备序列号')),
                ('DSize', models.IntegerField(default=0, verbose_name='USB设备大小')),
                ('DAction', models.IntegerField(default=0, verbose_name='1插入中、2已拔出')),
                ('Ctime', models.TextField(default='', verbose_name='插入时间')),
                ('Dtime', models.TextField(default='', verbose_name='拔出时间')),
                ('DType', models.IntegerField(default=0, verbose_name='是什么类别，移动盘还是U盘')),
                ('DStatus', models.IntegerField(default=0, verbose_name='状态')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.TextField(default='', verbose_name='USB设备名称')),
                ('SNumber', models.TextField(default='', verbose_name='USB设备序号')),
                ('UseTime', models.TextField(default='', verbose_name='USB设备使用时间')),
                ('DType', models.TextField(default='', verbose_name='USB设备类型')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DId', models.TextField(default='', verbose_name='计算ID')),
                ('DMac', models.TextField(default='', verbose_name='Mac地址')),
                ('DIp', models.TextField(default='', verbose_name='IP地址')),
                ('DName', models.TextField(default='', verbose_name='计算机名')),
                ('UName', models.TextField(default='', verbose_name='用户名')),
                ('DSystem', models.TextField(default='', verbose_name='计算机系统')),
                ('Remarks', models.TextField(default='', verbose_name='备注')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.TextField(default='', verbose_name='计算机ID')),
                ('FileType', models.IntegerField(default=0, verbose_name='1敏感文档 2木马')),
                ('KeyDesc', models.TextField(default='', verbose_name='命中关键字')),
                ('ContentRemark', models.TextField(default='', verbose_name='摘要')),
                ('FileName', models.TextField(default='', verbose_name='文件名')),
                ('FileSize', models.IntegerField(default=0, verbose_name='文件大小')),
                ('FileTag', models.IntegerField(default=0, verbose_name='1敏感、2木马、3重复、6伪装')),
                ('FileMd5', models.TextField(default='', verbose_name='文件MD5')),
                ('FileAttribute', models.TextField(default='', verbose_name='文件属性')),
                ('FileNumber', models.IntegerField(default=0, verbose_name='文件访问次数')),
                ('FileDesc', models.TextField(default='', verbose_name='文件描述')),
                ('PName', models.TextField(default='', verbose_name='进程名')),
                ('PUName', models.TextField(default='', verbose_name='进程用户名')),
                ('PPID', models.IntegerField(default=0, verbose_name='进程父PID')),
                ('PPName', models.TextField(default='', verbose_name='进程父进程名')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserFileCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.TextField(default='', verbose_name='计算机ID')),
                ('VName', models.TextField(default='', verbose_name='USB设备卷名')),
                ('DName', models.TextField(default='', verbose_name='USB设备名称')),
                ('DModel', models.TextField(default='', verbose_name='USB设备厂家')),
                ('SNumber', models.TextField(default='', verbose_name='USB设备序号')),
                ('Action', models.IntegerField(default=0, verbose_name='1拷入U盘、2拷出U盘')),
                ('ATime', models.TextField(default='', verbose_name='操作时间')),
                ('FileName', models.TextField(default='', verbose_name='文件名')),
                ('FileSize', models.IntegerField(default=0, verbose_name='大小')),
                ('FIleMD5', models.TextField(default='', verbose_name='MD5')),
                ('FileAttribute', models.TextField(default='', verbose_name='文件属性（可能是时间）')),
                ('FileDesc', models.TextField(default='', verbose_name='文件描述')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserNetWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.TextField(default='', verbose_name='计算机ID')),
                ('Domain', models.TextField(default='', verbose_name='域名')),
                ('IP', models.TextField(default='', verbose_name='IP')),
                ('Port', models.IntegerField(default=0, verbose_name='端口')),
                ('PName', models.TextField(default='', verbose_name='进程名')),
                ('FileMd5', models.TextField(default='', verbose_name='进程MD5')),
                ('IpName', models.TextField(default='', verbose_name='IP的地域')),
                ('IsHost', models.IntegerField(default=0, verbose_name='是不是本地')),
                ('IpAddress', models.TextField(default='', verbose_name='IP归属')),
                ('Action', models.IntegerField(default=0, verbose_name='国内还是国外')),
                ('xAddress', models.IntegerField(default=0, verbose_name='精度')),
                ('yAddress', models.IntegerField(default=0, verbose_name='精度')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.TextField(default='', verbose_name='计算机ID')),
                ('PID', models.IntegerField(default=0, verbose_name='进程ID')),
                ('PName', models.TextField(default='', verbose_name='进程名')),
                ('PCmd', models.TextField(default='', verbose_name='进程参数')),
                ('PSession', models.IntegerField(default=0, verbose_name='进程SessionID')),
                ('PUser', models.TextField(default='', verbose_name='进程用户名')),
                ('PMem', models.IntegerField(default=0, verbose_name='进程使用内存')),
                ('PIO', models.IntegerField(default=0, verbose_name='进程使用IO速率')),
                ('PVer', models.TextField(default='', verbose_name='进程版本')),
                ('PStart', models.TextField(default='', verbose_name='进程创建时间')),
                ('Verified', models.TextField(default='', verbose_name='进程签名')),
                ('IsVerified', models.IntegerField(default=0, verbose_name='进程是否签名')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccTime', models.TextField(default='', verbose_name='文件访问时间')),
                ('FileName', models.TextField(default='', verbose_name='文件名')),
                ('FilePath', models.TextField(default='', verbose_name='文件路径')),
                ('FileType', models.IntegerField(default=0, verbose_name='0文件不存在， 1文件，2目录')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField(default=0, verbose_name='进程ID')),
                ('SName', models.TextField(default='', verbose_name='服务名')),
                ('IName', models.TextField(default='', verbose_name='服务进程路径')),
                ('SCommand', models.TextField(default='', verbose_name='服务参数')),
                ('DName', models.TextField(default='', verbose_name='服务描述')),
                ('OName', models.TextField(default='', verbose_name='服务用户组')),
                ('Status', models.TextField(default='', verbose_name='服务当前状态')),
                ('StartUp', models.TextField(default='', verbose_name='服务是手动不是自动启')),
                ('SDesc', models.TextField(default='', verbose_name='服务描述')),
                ('FVer', models.TextField(default='', verbose_name='文件版本')),
                ('FPName', models.TextField(default='', verbose_name='文件厂家')),
                ('FCName', models.TextField(default='', verbose_name='文件公司')),
                ('FDesc', models.TextField(default='', verbose_name='文件描述')),
                ('DllName', models.TextField(default='', verbose_name='DLL信息')),
                ('IsRun', models.IntegerField(default=0, verbose_name='是否启动')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KRoot', models.TextField(default='', verbose_name='注册表主键')),
                ('KName', models.TextField(default='', verbose_name='注册表名')),
                ('KValue', models.TextField(default='', verbose_name='进程表值')),
                ('FName', models.TextField(default='', verbose_name='文件名')),
                ('FCommand', models.TextField(default='', verbose_name='文件参数')),
                ('FCName', models.TextField(default='', verbose_name='文件厂家')),
                ('Verified', models.TextField(default='', verbose_name='文件签名')),
                ('IsVerified', models.IntegerField(default=0, verbose_name='文件是否签名')),
                ('Other', models.TextField(default='', verbose_name='数据写入时间')),
            ],
        ),
        migrations.DeleteModel(
            name='fileinfo',
        ),
        migrations.DeleteModel(
            name='InstallApp',
        ),
        migrations.DeleteModel(
            name='IPvisit_Net',
        ),
        migrations.DeleteModel(
            name='NetApp',
        ),
        migrations.DeleteModel(
            name='PcInfo',
        ),
        migrations.DeleteModel(
            name='ProcList',
        ),
        migrations.DeleteModel(
            name='Recents',
        ),
        migrations.DeleteModel(
            name='RunInfo',
        ),
        migrations.DeleteModel(
            name='Security_Center',
        ),
        migrations.DeleteModel(
            name='ServiceList',
        ),
        migrations.DeleteModel(
            name='sTaskList',
        ),
        migrations.DeleteModel(
            name='stFileDownload_Net',
        ),
        migrations.DeleteModel(
            name='usb_conn',
        ),
        migrations.DeleteModel(
            name='usb_exchange',
        ),
        migrations.DeleteModel(
            name='UsbHistory',
        ),
        migrations.DeleteModel(
            name='WinUser',
        ),
    ]
