# Generated by Django 3.1.7 on 2021-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0006_auto_20210401_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelliAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.IntegerField(default=0, verbose_name='文件ID')),
                ('filename', models.TextField(verbose_name='文件名')),
                ('filetype', models.IntegerField(default=0, verbose_name='0文件不存在， 1文件，2目录')),
                ('action', models.IntegerField(choices=[(0, '下载'), (1, '打印'), (2, '拷贝')], verbose_name='行为')),
                ('Other', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
        ),
    ]
