# Generated by Django 3.1.7 on 2021-04-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0008_intellianalysis_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(default='', verbose_name='设备标志')),
                ('CacheName', models.TextField(default='', verbose_name='CacheName')),
                ('FileName', models.TextField(default='', verbose_name='')),
                ('JpgFileName', models.TextField(default='', verbose_name='')),
                ('ZipName', models.TextField(default='', verbose_name='')),
                ('FileEx', models.TextField(default='', verbose_name='')),
                ('SaveName', models.TextField(default='', verbose_name='')),
                ('MD5', models.TextField(default='', verbose_name='')),
                ('FileSize', models.IntegerField(default=0, verbose_name='')),
                ('ZipFileSize', models.IntegerField(default=0, verbose_name='')),
                ('JpgFileSize', models.IntegerField(default=0, verbose_name='')),
                ('UpSize', models.IntegerField(default='', verbose_name='')),
                ('IsOK', models.TextField(default='', verbose_name='')),
                ('IsZip', models.IntegerField(default=0, verbose_name='')),
                ('IsImge', models.IntegerField(default=0, verbose_name='')),
                ('InsterTime', models.TextField(default='', verbose_name='')),
            ],
        ),
    ]
