# Generated by Django 3.1.7 on 2021-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0010_userfile_isdup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intellianalysis',
            name='fileid',
        ),
        migrations.RemoveField(
            model_name='intellianalysis',
            name='filetype',
        ),
        migrations.AddField(
            model_name='intellianalysis',
            name='description',
            field=models.TextField(default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='intellianalysis',
            name='did',
            field=models.TextField(default=0, verbose_name='计算机ID'),
        ),
        migrations.AddField(
            model_name='intellianalysis',
            name='duplicate',
            field=models.BooleanField(default=False, verbose_name='是否重复'),
        ),
        migrations.AddField(
            model_name='intellianalysis',
            name='filesize',
            field=models.IntegerField(default=0, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='intellianalysis',
            name='md5',
            field=models.TextField(default='', verbose_name='MD5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intellianalysis',
            name='action',
            field=models.IntegerField(choices=[(0, '下载'), (1, '打印'), (2, '拷贝'), (3, '外发')], verbose_name='行为'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='FileTag',
            field=models.IntegerField(default=0, verbose_name='1敏感、2木马、3重复、4打印、6伪装'),
        ),
    ]
